class Paths(str):
    SALE_APARTMENTS = '/prodaja-stanova'
    SALE_HOUSES = '/prodaja-kuca'
    SALE_LANDS = 'prodaja-placeva'
    SALE_GARAGE = '/prodaja-garaza-i-parkinga'
    RENT_APARTMENTS = '/izdavanje-stanova'
    RENT_HOUSES = '/izdavanje-kuca'
    SALE_OFFICES = '/prodaja-poslovnih-prostora'
    NEW_BUILDINGS = '/novogradnja'
    MAILTO = 'mailto:info@4zida.rs'
