class Routes(str):
    SALE_APARTMENTS = '/prodaja-stanova'
    SALE_HOUSES = '/prodaja-kuca'
    SALE_LANDS = '/prodaja-placeva'
    SALE_GARAGE = '/prodaja-garaza-i-parkinga'
    SALE_OFFICES = '/prodaja-poslovnih-prostora'
    NEW_BUILDINGS = '/novogradnja'
    RENT_APARTMENTS = '/izdavanje-stanova'
    RENT_HOUSES = '/izdavanje-kuca'
    RENT_OFFICES = '/izdavanje-poslovnih-prostora'
    RENT_LANDS = '/izdavanje-placeva'
    RENT_GARAGE = '/izdavanje-garaza-i-parkinga'
