class HomePageLocators(str):
    HEADER_H1 = '//h1'
    HEADER_H2 = '//h2'
    HEADER_H3 = '//h3'
    HEADER_H3_QUICK_LINK = '//div[@test-data="premium-ads"]//h3'
    HEADER_H3_WIDGET = '//section[@test-data="blog-posts"]//h3'
    META_DESCRIPTION = '//meta[@name="description"]'
    META_ROBOTS = '//meta[@name="robots"]'
    LINK_CANONICAL = '//link[@rel="canonical"]'
    SEARCH_FORM = '//div[@test-data="search-form"]'
    FOOTER_LINKS = '//footer//a'
