class LoginFormLocators(str):
    LOGIN_DIALOG = '//div[@role="dialog"]'
    LOGIN_GOOGLE_IFRAME = '//div[@role="dialog"]//iframe'
    LOGIN_GOOGLE_BUTTON = '//div[@role="button"]'
    LOGIN_VIA_EMAIL_BUTTON = '//div[contains(@id, "login")]/button'
    LOGIN_EMAIL_INPUT = '//input[@name="email"]'
    LOGIN_PASSWORD_INPUT = '//input[@name="password"]'
    PASSWORD_INPUT = '//input[@name="plainPassword"]'
    CONFIRM_PASSWORD_INPUT = '//input[@name="confirmPlainPassword"]'
    FIRST_NAME_INPUT = '//input[@name="firstName"]'
    LOGIN_SUBMIT_BUTTON = '//button[@type="submit"]'
    REGISTER_SECTION = '//div[contains(@id, "register")]/section'
    REGISTER_FORM = '//div[contains(@id, "register")]//form'
    REGISTER_NEW_USER_BUTTON = '//button[contains(@id, "register")]'
    CONTINUE_WITH_EMAIL = '//div[contains(@id, "register")]//button'
    USER_AGREEMENT_CHECKBOX = '//div[contains(@id, "register")]//button[@role="checkbox"]'
    REGISTER_SUBMIT_BUTTON = '//div[contains(@id, "register")]//button[@type="submit"]'
