class SearchFormLocators(str):
    SEARCH_FORM = '//div[@test-data="search-form"]'
    SEARCH_FORM_TAB_SALE = f'{SEARCH_FORM}//button[contains(@id, "sale")]'
    SEARCH_FORM_TAB_RENT = f'{SEARCH_FORM}//button[contains(@id, "rent")]'
    SEARCH_FORM_COMBOBOX_TYPE = f'{SEARCH_FORM}//button[@role="combobox"]'
    SEARCH_FORM_COMBOBOX_TYPE_INPUT = f'{SEARCH_FORM}//button[@role="combobox"]/span[2]'
    SEARCH_FORM_TYPE_APARTMENT_OPTION = f'{SEARCH_FORM}//option[@value="apartment"]'
    SEARCH_FORM_TYPE_HOUSE_OPTION = f'{SEARCH_FORM}//option[@value="house"]'
    SEARCH_FORM_TYPE_OFFICE_OPTION = f'{SEARCH_FORM}//option[@value="office"]'
    SEARCH_FORM_TYPE_LOT_OPTION = f'{SEARCH_FORM}//option[@value="lot"]'
    SEARCH_FORM_TYPE_VEHICLESPOT_OPTION = f'{SEARCH_FORM}//option[@value="vehiclespot"]'
    SEARCH_FORM_TYPE_APARTMENT = '//div[@data-radix-popper-content-wrapper]//span[text()="Stanovi"]'
    SEARCH_FORM_TYPE_HOUSE = '//div[@data-radix-popper-content-wrapper]//span[text()="Kuće"]'
    SEARCH_FORM_TYPE_OFFICE = '//div[@data-radix-popper-content-wrapper]//span[text()="Poslovni prostori"]'
    SEARCH_FORM_TYPE_LOT = '//div[@data-radix-popper-content-wrapper]//span[text()="Placevi"]'
    SEARCH_FORM_TYPE_VEHICLESPOT = '//div[@data-radix-popper-content-wrapper]//span[text()="Garaže/parking"]'
    SEARCH_FORM_PRICE_TO_INPUT = f'{SEARCH_FORM}//input[@name="priceTo"]'
    SEARCH_FORM_M2_FROM_INPUT = f'{SEARCH_FORM}//input[@name="m2From"]'
    SEARCH_FORM_SEARCH_BUTTON = f'{SEARCH_FORM}/button'
    SEARCH_FORM_COMBOBOX_SUBTYPE_TITLE = f'{SEARCH_FORM}//div[3]//button/span[2]'
    SEARCH_FORM_COMBOBOX_SUBTYPE_SELECT = f'{SEARCH_FORM}//ul'
    SEARCH_FORM_COMBOBOX_SUBTYPE_OPTION = f'{SEARCH_FORM}//ul//li'
    SEARCH_FORM_COMBOBOX_SUBTYPE_INPUT = f'{SEARCH_FORM}//div[3]//button/span[1]'
