name: Run Selenium Automated Tests

on: 
  workflow_dispatch

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Run Tests with Docker
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start Containers
      run: docker-compose -f "docker-compose.yml" up --build --exit-code-from tests

    - name: Stop Containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down

    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: ./allure-results
        retention-days: 3

    - name: Upload Performance Results
      uses: actions/upload-artifact@v4
      with:
        name: performance-results
        path: ./performance-results
        retention-days: 3

    - name: Get Performance History
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        token: ${{ secrets.GH_TOKEN }}
        ref: perf-results
        path: perf-results

    - name: Download Performance Results
      uses: actions/download-artifact@v3
      with:
        name: Upload Performance Results

    - name: Save Performance Results
      uses: fregante/setup-git-user@v2

    - name: Test
      run: |
        git config user.name github-actions
        git config user.email ${{ github.event.sender.email }}
        git pull
        git add ./performance-results/*
        git commit -m "Automated commit"
        git push

    - name: Get Allure History
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Save History and Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 30

    - name: Deploy Allure Report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
