name: Run Selenium Automated Tests

on: 
  workflow_dispatch

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start Containers
      run: docker-compose -f "docker-compose.yml" up --build --exit-code-from tests

    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: ./allure-results
        retention-days: 3

    - name: Upload Performance Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-results
        path: ./performance-results
        retention-days: 3

    - name: Get Allure History
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      # id: allure-report
      with:
        allure_results: build/allure-results
        gh_pages: gh-pages
        # allure_report: allure-report
        allure_history: allure-history
        # keep_reports: 30

    - name: Stop Containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down

    - name: Publish Allure Report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history

  commit_results:
    runs-on: ubuntu-latest
    name: Save Performance Metrics
    if: always()
    needs: [docker]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: main
      - uses: actions/download-artifact@v4
        with:
          name: performance-results
          path: performance-metrics/
      - uses: fregante/setup-git-user@v2
      - run: |
          git config user.name github-actions
          git config user.email ${{ github.event.sender.email }}
          git pull
          git add "**/metrics_*.json"
          git commit -m "Automated commit"
          git push
